import { createHash } from 'crypto';
import { AppConfig } from '../../src/config/env';

export function createTestConfig(databaseUrl: string, namespace: string): AppConfig {
  return {
    environment: 'test',
    port: 0,
    databaseUrl,
    allowedOrigins: ['http://localhost:8081'],
    trustProxy: false,
    jsonBodyLimit: '256kb',
    secrets: {
      source: 'LOCAL_ENV',
      bundleVersion: null,
    },
    operations: {
      runtimeDatabaseRole: null,
      backupProvider: null,
      lastRestoreVerifiedAt: null,
      maximumRestoreAgeDays: 30,
      rpoMinutes: 60,
      rtoMinutes: 240,
      observabilityProvider: null,
      alertingEnabled: false,
    },
    jwt: {
      accessSecret: `${namespace}-jwt-secret-with-sufficient-entropy-for-integration-tests`,
      issuer: `ruta-emocional-${namespace}`,
      audience: 'ruta-emocional-app-test',
      accessTtlSeconds: 900,
      refreshTtlDays: 30,
    },
    password: {
      pepper: `${namespace}-password-pepper-with-sufficient-entropy-for-tests`,
      scryptN: 16_384,
      scryptR: 8,
      scryptP: 1,
      keyLength: 32,
    },
    professionalDirectory: {
      defaultPageSize: 20,
      maxPageSize: 50,
      maxRadiusKm: 100,
      maxAvailabilityWindowDays: 31,
      maxWeeklyRules: 50,
      publicRequestsPerMinute: 120,
      supportedCurrencies: ['NIO'],
    },
    localQa: {
      enabled: false,
      evidenceDirectory: null,
      evidenceMaximumBytes: 5_242_880,
      evidenceUploadsPerMinute: 5,
    },
    requestFlow: {
      minimumAmount: '100.00',
      maximumAmount: '10000.00',
      immediateTtlMinutes: 30,
      scheduledLeadMinutes: 120,
      scheduledOfferCutoffMinutes: 30,
      maximumScheduleDays: 90,
      locationRetentionHours: 24,
      maximumOpenImmediateRequests: 1,
      maximumDescriptionLength: 2000,
      maximumPrimaryNeedLength: 240,
      maximumOfferMessageLength: 500,
      defaultPageSize: 20,
      maximumPageSize: 50,
      idempotencyTtlHours: 24,
      expirationBatchSize: 100,
      mutationsPerMinute: 60,
      serializableMaxRetries: 3,
      serializableRetryBaseDelayMs: 5,
      supportedCurrencies: ['NIO'],
    },
    messaging: {
      maximumTextLength: 4000,
      defaultPageSize: 50,
      maximumPageSize: 100,
      messagesPerMinute: 60,
      maximumSocketSubscriptions: 10,
      socketAuthRevalidationSeconds: 60,
      outboxPollIntervalMs: 50,
      outboxBatchSize: 20,
      outboxClaimTtlSeconds: 10,
      outboxMaximumAttempts: 3,
      outboxRetryBaseDelayMs: 10,
      outboxReadinessMaximumLagSeconds: 120,
    },
    appointments: {
      durationMinutes: 50,
      slotIntervalMinutes: 10,
      minimumLeadMinutes: 0,
      maximumHorizonDays: 90,
      patientCancellationNoticeMinutes: 60,
      startWindowBeforeMinutes: 15,
      maximumCancellationReasonLength: 500,
      defaultPageSize: 20,
      maximumPageSize: 50,
      mutationsPerMinute: 60,
      idempotencyTtlHours: 24,
      serializableMaxRetries: 3,
      serializableRetryBaseDelayMs: 5,
      reminderMinutesBefore: [1440, 60],
    },
    clinical: {
      contentEncryptionKeys: {
        1: createHash('sha256').update(namespace).digest('base64'),
      },
      activeContentEncryptionKeyVersion: 1,
      maximumNoteLength: 20_000,
      maximumEncounterReasonLength: 500,
      maximumTreatmentSummaryLength: 5_000,
      maximumGoalLength: 1_000,
      maximumGoalsPerPlan: 20,
      minimumAmendmentReasonLength: 10,
      maximumAmendmentReasonLength: 500,
      maximumEncounterDurationMinutes: 480,
      encounterFutureSkewMinutes: 15,
      defaultPageSize: 20,
      maximumPageSize: 50,
      mutationsPerMinute: 60,
      idempotencyTtlHours: 24,
      serializableMaxRetries: 3,
      serializableRetryBaseDelayMs: 5,
    },
    triage: {
      enabled: true,
      protocolApproved: true,
      protocolApproval: null,
      externalProviderEnabled: false,
      evaluatorVersion: 'test-evaluator-1.0.0',
      consentDocumentCode: 'MENTA_ORIENTATION',
      consentDocumentVersion: '1.0.0',
      defaultCountryCode: 'NI',
      crisisResources: {
        NI: [{
          code: 'TEST_EMERGENCY',
          label: 'Recurso de emergencia de prueba',
          channel: 'PHONE',
          value: '118',
          sourceUrl: 'https://example.test/emergency-source',
          verifiedAt: '2026-08-30',
          reviewDueAt: '2026-11-30',
          owner: 'Equipo de operaciones de prueba',
        }],
      },
      safetyActions: {
        HIGH: ['Contacta de inmediato a una persona de confianza y busca apoyo profesional urgente.'],
        CRITICAL: ['Contacta ahora un servicio de emergencia y no permanezcas a solas.'],
      },
      maximumProviderSummaryLength: 1_000,
      assessmentsPerMinute: 60,
      idempotencyTtlHours: 24,
      retentionPolicy: {
        approved: false,
        version: 'PENDING',
        assessmentRetentionDays: 0,
        erasureRequestSlaBusinessDays: 5,
      },
    },
  };
}
