import { StyleSheet } from 'react-native';

import { Colors } from '../../theme/colors';
import { BorderRadius, Spacing } from '../../theme/spacing';
import { FontFamily, Typography } from '../../theme/typography';

export const clinicalRecordsStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.xl,
    paddingBottom: Spacing.base,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.divider,
  },
  flex: { flex: 1, minWidth: 0 },
  title: { ...Typography.h1, color: Colors.textPrimary },
  subtitle: { ...Typography.bodySmall, color: Colors.textSecondary, marginTop: Spacing.xs },
  securityMark: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primaryTint,
  },
  securityText: { ...Typography.caption, color: Colors.primary, fontFamily: FontFamily.bodySemiBold },
  content: { padding: Spacing.base, paddingBottom: Spacing.xxxl },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  supportingText: { ...Typography.body, color: Colors.textSecondary, marginTop: Spacing.md },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    marginBottom: Spacing.base,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.errorSurface,
    borderWidth: 1,
    borderColor: Colors.errorBorder,
  },
  errorText: { ...Typography.bodySmall, color: Colors.error, flex: 1 },
  emptyState: { alignItems: 'center', paddingVertical: Spacing.giant, paddingHorizontal: Spacing.xl },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primaryTint,
    marginBottom: Spacing.base,
  },
  emptyTitle: { ...Typography.h3, color: Colors.textPrimary },
  emptyText: { ...Typography.body, color: Colors.textSecondary, textAlign: 'center', marginTop: Spacing.sm },
  patientStrip: { marginHorizontal: -Spacing.base, paddingHorizontal: Spacing.base, marginBottom: Spacing.lg },
  patientChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    minWidth: 170,
    marginRight: Spacing.sm,
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    backgroundColor: Colors.surface,
  },
  patientChipSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primaryTint,
  },
  avatarSelected: { backgroundColor: Colors.primaryOverlay },
  patientName: { ...Typography.body, color: Colors.textPrimary, fontFamily: FontFamily.bodySemiBold },
  patientNameSelected: { color: Colors.textInverse },
  patientMeta: { ...Typography.caption, color: Colors.textTertiary, marginTop: Spacing.xxs },
  patientMetaSelected: { color: Colors.primaryTintStrong },
  recordLoader: { marginVertical: Spacing.xxxl },
  recordHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.lg,
  },
  recordTitle: { ...Typography.h2, color: Colors.textPrimary },
  recordCaption: { ...Typography.bodySmall, color: Colors.textSecondary, marginTop: Spacing.xxs },
  primaryIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
  },
  triageLauncher: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.base,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.primaryTintStrong,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.primaryTint,
  },
  triageLauncherTitle: { ...Typography.h4, color: Colors.primary },
  triageLauncherText: { ...Typography.bodySmall, color: Colors.textSecondary, marginTop: Spacing.xxs },
  triageCard: {
    gap: Spacing.md,
    padding: Spacing.base,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.primaryTintStrong,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.surfaceRaised,
  },
  triageHeading: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  triageIcon: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.primaryTint,
  },
  triageTitle: { ...Typography.h4, color: Colors.textPrimary },
  triageMeta: { ...Typography.caption, color: Colors.textSecondary, marginTop: Spacing.xxs },
  triageSummary: { ...Typography.body, color: Colors.textPrimary },
  triageTransparency: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm },
  triageTransparencyText: { ...Typography.caption, color: Colors.textTertiary, flex: 1 },
  reviewedMark: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingTop: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.divider,
  },
  reviewedText: { ...Typography.bodySmall, fontFamily: FontFamily.bodySemiBold, color: Colors.success },
  secondaryIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primaryTint,
  },
  pressed: { opacity: 0.75 },
  editorPanel: {
    padding: Spacing.base,
    marginBottom: Spacing.xl,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    backgroundColor: Colors.surfaceRaised,
  },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionHeadingWithAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.lg,
    marginBottom: Spacing.md,
  },
  sectionTitle: { ...Typography.h3, color: Colors.textPrimary },
  sectionCaption: { ...Typography.bodySmall, color: Colors.textSecondary, marginTop: Spacing.xxs },
  inputLabel: { ...Typography.label, color: Colors.textSecondary, marginTop: Spacing.base, marginBottom: Spacing.sm },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    color: Colors.textPrimary,
    ...Typography.body,
  },
  textArea: {
    minHeight: 110,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    color: Colors.textPrimary,
    textAlignVertical: 'top',
    ...Typography.body,
  },
  compactTextArea: {
    minHeight: 76,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    color: Colors.textPrimary,
    textAlignVertical: 'top',
    ...Typography.body,
  },
  noteArea: {
    minHeight: 180,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    borderRadius: BorderRadius.md,
    padding: Spacing.md,
    color: Colors.textPrimary,
    textAlignVertical: 'top',
    ...Typography.body,
  },
  editorActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.sm, marginTop: Spacing.base },
  inlineEmpty: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.base,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.surfaceSoft,
  },
  inlineEmptyText: { ...Typography.bodySmall, color: Colors.textSecondary, flex: 1 },
  planCard: {
    padding: Spacing.base,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cardTopRow: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm },
  planSummary: { ...Typography.body, color: Colors.textPrimary, fontFamily: FontFamily.bodySemiBold },
  cardDate: { ...Typography.caption, color: Colors.textTertiary, marginTop: Spacing.xs },
  statusPill: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.primaryTint,
  },
  statusText: { ...Typography.caption, color: Colors.primary, fontFamily: FontFamily.bodySemiBold },
  goalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.divider,
  },
  goalText: { ...Typography.bodySmall, color: Colors.textPrimary },
  goalStatus: { ...Typography.caption, color: Colors.textTertiary, marginTop: Spacing.xxs },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  timelineHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.xl,
    marginBottom: Spacing.md,
  },
  encounterCard: { flexDirection: 'row' },
  timelineRail: { width: 26, alignItems: 'center' },
  timelineDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: Colors.primary, marginTop: Spacing.lg },
  timelineLine: { width: 1, flex: 1, backgroundColor: Colors.borderStrong, marginTop: Spacing.xs },
  encounterBody: {
    flex: 1,
    minWidth: 0,
    padding: Spacing.base,
    marginBottom: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  encounterDate: { ...Typography.h4, color: Colors.textPrimary },
  noteText: { ...Typography.body, color: Colors.textSecondary, marginTop: Spacing.md, lineHeight: 22 },
  noteMeta: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginTop: Spacing.md },
  metaText: { ...Typography.caption, color: Colors.textTertiary },
  dot: { width: 3, height: 3, borderRadius: 2, backgroundColor: Colors.textTertiary, marginHorizontal: Spacing.xs },
  versionPanel: { marginTop: Spacing.base, paddingTop: Spacing.md, borderTopWidth: 1, borderTopColor: Colors.divider },
  versionItem: {
    paddingVertical: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.divider,
  },
  versionTitle: { ...Typography.bodySmall, color: Colors.primary, fontFamily: FontFamily.bodySemiBold },
  versionDate: { ...Typography.caption, color: Colors.textTertiary },
  versionAuthor: { ...Typography.caption, color: Colors.textSecondary, marginTop: Spacing.xs },
  versionContent: { ...Typography.bodySmall, color: Colors.textPrimary, marginTop: Spacing.sm },
  amendmentBox: {
    padding: Spacing.sm,
    marginTop: Spacing.sm,
    borderRadius: BorderRadius.sm,
    backgroundColor: Colors.warningSurface,
  },
  amendmentLabel: { ...Typography.label, color: Colors.warning },
  amendmentText: { ...Typography.bodySmall, color: Colors.textSecondary, marginTop: Spacing.xs },
});
